#!/bin/bash
FLOOR=1
RANGE=5
trial_number=0   #initialize
until [ "$trial_number" -gt $FLOOR ]
do
  trial_number=$RANDOM
  let "trial_number %= $RANGE"  # Scales $number down within $RANGE.
done

echo "tries $trial_number"
server_address=0
flag_server_found=0
ip_subnet=$(ip ....)
for ((tries=1; tries<=trial_number; tries++))
do
	for(hostno=0; hostno<255; hostno++)
	do
		./server-test "$ip_subnet.$hostno"
		if[ "$1" == 0]
		then
			server_address="$ip_subnet.$hostno"
			flag_server_found=1
			break
		fi
	done
done



if [ "$flag_server_found" == 1 ]
then
	echo "Sensor-APP"
	#./client $test

else
	echo "Starting server as daemon"
	./server -d
	echo LCD-APP
fi




